cmake_minimum_required(VERSION 4.1)
project(struct_data)

set(CMAKE_CXX_STANDARD 20)

add_executable(struct_data main.cpp
        lab-01/task1.cpp
        lab-01/lab1.h
        lab-02/task1.cpp
        lab-02/lab2.h
        lab-02/task2.cpp
        lab-02/task3.cpp
        lab-02/task4.cpp
        lab-03/task1.cpp
        lab-03/lab3.h
        lab-03/task2.cpp
        lab-03/task3.cpp
        lab-04/lab4.h
        lab-04/task1.cpp
        lab-05/task1.cpp
        lab-05/lab5.h
        lab-05/task2.cpp
        lab-05/task3.cpp
        lab-06/task1.cpp
        lab-06/lab6.h
        lab-06/task2.cpp
        lab-06/task3.cpp
        lab-06/task4.cpp
)
#lab2/task2_lab2.h
