cmake_minimum_required(VERSION 4.1)
project(struct_data)

set(CMAKE_CXX_STANDARD 20)

add_executable(struct_data main.cpp
        lab-01/task1.cpp
        lab-01/lab1.h
        lab-02/task1.cpp
        lab-02/lab2.h
        lab-02/task2.cpp
        lab-02/task3.cpp
        lab-02/task4.cpp
        lab-03/task1.cpp
        lab-03/lab3.h
        lab-03/task2.cpp
        lab-03/task3.cpp
        lab-04/lab4.h
        lab-04/task1.cpp
        lab-05/task1.cpp
        lab-05/lab5.h
        lab-05/task2.cpp
        lab-05/task3.cpp
        lab-06/task1.cpp
        lab-06/lab6.h
        lab-06/task2.cpp
        lab-06/task3.cpp
        lab-06/task4.cpp
        lab-07/lab7.h
        lab-07/task1.cpp
        lab-07/task2.cpp
        lab-08/lab8.h
        lab-08/task1.cpp
        lab-08/task2.cpp
        lab-09/lab9.h
        lab-09/task1.cpp
        "lab-09/task2(test).cpp"
        lab-09/2.cpp
        lab-09/task2.cpp
        lab-10/lab10.h
        lab-10/task1.cpp
        lab-11/lab11.h
        lab-11/task1.cpp
        lab-12/task1.cpp
        lab-12/lab12.h
        lab-12/task2.cpp
        lab-12/task3.cpp
        lab-13/task1.cpp
        lab-13/lab13.h
        lab-13/task2.cpp
        lab-13/task3.cpp
        lab-13/task4.cpp
        lab-13/task5.cpp
        lab-14/lab14.h
        lab-14/task1.cpp
        lab-14/task2.cpp
        lab-14/task3.cpp
        lab-14/task4.cpp
        lab-15/task1.cpp
        lab-15/lab15.h
        lab-15/task2.cpp
        lab-15/task3.cpp
        lab-16/task1.cpp
        lab-16/lab16.h
        lab-16/task2.cpp
        lab-17/task1.cpp
        lab-17/lab17.h
        lab-18/lab18.h
        lab-18/task1.cpp
        lab-18/task2.cpp
        lab-18/task3.cpp
        lab-18/task4.cpp
        lab-18/task5.cpp
        lab-18/5.cpp
        lab-18/6.cpp
        lab-20/task1.cpp
        lab-20/lab20.h
        lab-20/task2.cpp
)
#lab2/task2_lab2.h
